/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socialmusicclient;

//import javax.swing.JTextField;
import javax.swing.DefaultListModel;
import java.awt.Component;
import java.awt.PopupMenu;
import java.util.*;

/**
 *
 * @author Student
 */
public class MainPage extends javax.swing.JFrame
{

	private Vector<String> Friends = new Vector<String>();
	//private Vector<String> FriendRequests = new Vector<String>();

	static void addFriendRequests(String people)
	{
		if (!FriendRequests.contains(people))
		{
			FriendRequests.add(people);
		}
	}

	static Vector<String> FriendRequests;
	static Vector<String> Posts;

	/*private JTextField userField;

    // then create setters and getter
    public void setUsername(String username) {this.userField.setText(username);}
    public String getUsername() {return this.userField.getText();}*/
	public String username_;
	public String information_;
	public String targetUsername_;

	private SocketConnection server_;

	public MainPage(SocketConnection server, String username, String information)
	{
		initComponents();
		username_ = username; // set field to passed in username
		information_ = information;
		server_ = server;

		server_.send("REGS FRIENDS pass dob pob 1 2 3\n");
		server_.send("ADDR a FRIENDS\n");

		//s.send("DELR " +Selection.toString() + "\n");
		UpdateEverything();
		//String[] FriendRequestsList = { "Branden", "Barnaby", "Torrie", "Moore" };
		/*
		String[] people = { "Branden", "Barnaby", "Moore", "Torrie", "Elise" };

		FriendRequests = new Vector<String>();

		for (int i = 0; i < people.length; i++) {
			addFriendRequests(people[i]);
		}
		for (int j = 0; j < people.length; j++) {
			addFriendRequests(people[j]);
		}
		FriendRequestsLst.setListData(FriendRequests);
		InformationTA.append(information);
		 */
		jInternalFrame1.setTitle("NTU Music Social Network: " + username);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FriendsLst = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        InformationTA = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        SharedSongsLst = new javax.swing.JList<>();
        PlayBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PostTxt = new javax.swing.JTextField();
        SendBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ServerLst = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        FriendRequestsLst = new javax.swing.JList<>();
        RequestFriendshipBtn = new javax.swing.JButton();
        ChatBtn = new javax.swing.JButton();
        AcceptBtn = new javax.swing.JButton();
        RefuseBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        PostsLst = new javax.swing.JList<>();
        RemoveFriendBtn = new javax.swing.JButton();
        DeletePostBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("NTU Music Social Network: ");
        jInternalFrame1.setVisible(true);

        jLabel1.setText("Friends");

        jScrollPane1.setViewportView(FriendsLst);

        jLabel2.setText("Information");

        jLabel3.setText("Shared Songs");

        InformationTA.setColumns(20);
        InformationTA.setRows(5);
        jScrollPane2.setViewportView(InformationTA);

        jScrollPane3.setViewportView(SharedSongsLst);

        PlayBtn.setText("Play");

        jLabel4.setText("Friend Posts");

        jLabel5.setText("Post:");

        SendBtn.setText("Send");
        SendBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SendBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("People on your Server");

        jLabel7.setText("Friend Requests From");

        jScrollPane5.setViewportView(ServerLst);

        jScrollPane6.setViewportView(FriendRequestsLst);

        RequestFriendshipBtn.setText(" Request Friendship");
        RequestFriendshipBtn.setToolTipText("");

        ChatBtn.setText("Chat");
        ChatBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ChatBtnActionPerformed(evt);
            }
        });

        AcceptBtn.setText("Accept");
        AcceptBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AcceptBtnActionPerformed(evt);
            }
        });

        RefuseBtn.setText("Refuse");
        RefuseBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RefuseBtnActionPerformed(evt);
            }
        });

        LogOutBtn.setText("Log out");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LogOutBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                UpdateBtnActionPerformed(evt);
            }
        });

        jScrollPane7.setViewportView(PostsLst);

        RemoveFriendBtn.setText("Remove");
        RemoveFriendBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RemoveFriendBtnActionPerformed(evt);
            }
        });

        DeletePostBtn.setText("Delete Post");
        DeletePostBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                DeletePostBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PostTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RequestFriendshipBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SendBtn)
                                    .addComponent(AcceptBtn)
                                    .addComponent(RefuseBtn)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UpdateBtn)
                                .addGap(34, 34, 34)
                                .addComponent(LogOutBtn))))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RemoveFriendBtn)
                            .addComponent(ChatBtn))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlayBtn)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(39, 39, 39))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeletePostBtn)
                .addGap(121, 121, 121))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(RemoveFriendBtn)
                        .addGap(18, 18, 18)
                        .addComponent(ChatBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlayBtn)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeletePostBtn))
                .addGap(4, 4, 4)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PostTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SendBtn))
                .addGap(28, 28, 28)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(AcceptBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RefuseBtn))
                    .addComponent(RequestFriendshipBtn)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LogOutBtn)
                        .addComponent(UpdateBtn)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendBtnActionPerformed
		String Post;
		Post = PostTxt.getText();
		PostTxt.setText("");
		if (Post.isEmpty())
		{
			return;
		} else
		{
			Post = "ADDP " + username_ + " \"" + Post + "\"" + "\n";

			server_.send(Post);

			System.out.println("UpdateEverything");

			UpdateEverything();
		}

		// TODO add your handling code here:
    }//GEN-LAST:event_SendBtnActionPerformed

    private void ChatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChatBtnActionPerformed

		Object Selection = FriendsLst.getSelectedValue();
		targetUsername_ = Selection.toString();

		new PrivateChat(server_, username_, targetUsername_).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ChatBtnActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
		this.setVisible(false);
		new Login(server_).setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void AcceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBtnActionPerformed
		Object Selection = FriendRequestsLst.getSelectedValue();
		//Object Selection

		if (Friends.contains(Selection.toString()))
		{
			return;
		}

		Friends.add(Selection.toString());
		FriendsLst.setListData(Friends);
		FriendRequests.removeElement(Selection);
		FriendRequestsLst.setListData(FriendRequests);

		server_.send("ADDF " + Selection.toString() + "\n");
		server_.send("DELR " + Selection.toString() + "\n");

// TODO add your handling code here:
    }//GEN-LAST:event_AcceptBtnActionPerformed

    private void RefuseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefuseBtnActionPerformed
		Object Selection = FriendRequestsLst.getSelectedValue();
		FriendRequests.remove(Selection);
		FriendRequestsLst.setListData(FriendRequests);

		server_.send("DELR " + Selection.toString() + "\n");
		UpdateEverything();

// TODO add your handling code here:
    }//GEN-LAST:event_RefuseBtnActionPerformed

    private void RemoveFriendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveFriendBtnActionPerformed
		Object Selection = FriendsLst.getSelectedValue();
		Friends.remove(Selection);
		FriendsLst.setListData(Friends);

		server_.send("DELF " + Selection.toString() + "\n");
		UpdateEverything();
    }//GEN-LAST:event_RemoveFriendBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
		UpdateEverything();  // TODO add your handling code here:
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void DeletePostBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletePostBtnActionPerformed
		Object Selection = PostsLst.getSelectedValue();
		Posts.remove(Selection);
		PostsLst.setListData(Posts);

		server_.send("DELP " + Selection.toString() + "\n");
		UpdateEverything();
    }//GEN-LAST:event_DeletePostBtnActionPerformed

	private void UpdateEverything()
	{
		System.out.println("UpdateEverything");

		String[] friends = server_.send("FRND " + username_).split("\\s+");
		FriendsLst.setListData(friends);

		String[] friendreqs = server_.send("REQS " + username_).split("\\s+");
		FriendRequestsLst.setListData(friendreqs);


		String[] PostsArr = server_.send("GETP " + "\n").split("\\t");
		
		if(PostsArr[0].equals("POSTS"))
		{
			Vector<String> posts = new Vector<>();
			
			for(int i = 1; i < PostsArr.length; ++i)
			{
				posts.add(PostsArr[i]);
			}

			PostsLst.setListData(posts);
		}

		String[] OnlinePeopleArr = server_.send("ONLN " + username_).split("\\s+");
		
		System.out.format("OnlinePeopleArr size: %d\n", OnlinePeopleArr.length);
		
		for(int i = 0; i < OnlinePeopleArr.length; ++i)
		{
			System.out.println(OnlinePeopleArr[i]);
		}

		if(OnlinePeopleArr[0].equals("FRIENDS") && OnlinePeopleArr.length > 1)
		{
			Vector<String> OnlinePeople = new Vector<>();

			for(int i = 1; i < OnlinePeopleArr.length; ++i)
			{
				System.out.println(OnlinePeopleArr[i]);
				OnlinePeople.add(OnlinePeopleArr[i]);
			}

			ServerLst.setListData(OnlinePeople);
		}
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptBtn;
    private javax.swing.JButton ChatBtn;
    private javax.swing.JButton DeletePostBtn;
    private javax.swing.JList<String> FriendRequestsLst;
    private javax.swing.JList<String> FriendsLst;
    private javax.swing.JTextArea InformationTA;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JButton PlayBtn;
    private javax.swing.JTextField PostTxt;
    private javax.swing.JList<String> PostsLst;
    private javax.swing.JButton RefuseBtn;
    private javax.swing.JButton RemoveFriendBtn;
    private javax.swing.JButton RequestFriendshipBtn;
    private javax.swing.JButton SendBtn;
    private javax.swing.JList<String> ServerLst;
    private javax.swing.JList<String> SharedSongsLst;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
