/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socialmusicclient;

import javax.swing.DefaultListModel;
import java.awt.Component;
import java.awt.PopupMenu;
import java.util.*;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author N0574076
 */
public class NewRegistration extends javax.swing.JFrame
{

	public String information;
	private Vector<Integer> MusicList = new Vector<>();
	private Vector<String> MusicListString = new Vector<>();

	private SocketConnection server_;

	List<String> MusicTypes = new ArrayList<>();

	/**
	 * Creates new form NewRegistration
	 */
	public NewRegistration(SocketConnection server)
	{
		initComponents();
		
		server_ = server;

		MusicTypes.add("Alternative");
		MusicTypes.add("Blues");
		MusicTypes.add("Classical");
		MusicTypes.add("Country");
		MusicTypes.add("Dance");
		MusicTypes.add("Easy Listening");
		MusicTypes.add("Electronic");
		MusicTypes.add("Folk");
		MusicTypes.add("Hip Hop / Rap");
		MusicTypes.add("Indie Pop");
		MusicTypes.add("Gospel");
		MusicTypes.add("Asian Pop");
		MusicTypes.add("Jazz");
		MusicTypes.add("Latin");
		MusicTypes.add("Opera");
		MusicTypes.add("Pop (Popular music)");
		MusicTypes.add("R&B / Soul");
		MusicTypes.add("Reggae");
		MusicTypes.add("Rock");
		MusicTypes.add("World Music / Beats");

		MusicProfileCmb.setModel(new DefaultComboBoxModel(MusicTypes.toArray()));

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RegUsernameTxt = new javax.swing.JTextField();
        PlaceOfBirthTxt = new javax.swing.JTextField();
        DateOfBirthTxt = new javax.swing.JTextField();
        MusicProfileCmb = new javax.swing.JComboBox<>();
        AddButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MusicProfileList = new javax.swing.JList<>();
        RegisterButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RegPasswordTxt = new javax.swing.JTextField();
        registerStatus = new javax.swing.JLabel();
        RemoveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("Music Social Network - New Registration");
        jInternalFrame1.setToolTipText("");
        jInternalFrame1.setVisible(true);

        jLabel1.setText("Username");

        jLabel2.setText("Place of Birth");

        jLabel3.setText("Date of Birth");

        jLabel4.setText("Music Profile");

        RegUsernameTxt.addCaretListener(new javax.swing.event.CaretListener()
        {
            public void caretUpdate(javax.swing.event.CaretEvent evt)
            {
                RegUsernameTxtCaretUpdate(evt);
            }
        });

        PlaceOfBirthTxt.addCaretListener(new javax.swing.event.CaretListener()
        {
            public void caretUpdate(javax.swing.event.CaretEvent evt)
            {
                PlaceOfBirthTxtCaretUpdate(evt);
            }
        });

        DateOfBirthTxt.addCaretListener(new javax.swing.event.CaretListener()
        {
            public void caretUpdate(javax.swing.event.CaretEvent evt)
            {
                DateOfBirthTxtCaretUpdate(evt);
            }
        });

        MusicProfileCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jazz", "Pop", "Country", "Rock", "Metal" }));

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AddButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(MusicProfileList);

        RegisterButton.setText("Register");
        RegisterButton.setEnabled(false);
        RegisterButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RegisterButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");

        jLabel5.setText("or");

        jLabel6.setText("Password");

        RegPasswordTxt.addCaretListener(new javax.swing.event.CaretListener()
        {
            public void caretUpdate(javax.swing.event.CaretEvent evt)
            {
                RegPasswordTxtCaretUpdate(evt);
            }
        });

        RemoveBtn.setText("Remove");
        RemoveBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RemoveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RegisterButton)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerStatus)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CancelButton))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RegPasswordTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlaceOfBirthTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(RegUsernameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateOfBirthTxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(76, 76, 76)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RemoveBtn))
                            .addComponent(jLabel4)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(MusicProfileCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddButton)))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(MusicProfileCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(RegUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(PlaceOfBirthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(DateOfBirthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(RegPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(registerStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegisterButton)
                            .addComponent(CancelButton)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(AddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RemoveBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed

		String RegUsername = "";
		String RegPassword = "";
		String DOB = "";
		String POB = "";

		RegUsername = RegUsernameTxt.getText();
		RegPassword = RegPasswordTxt.getText();
		DOB = DateOfBirthTxt.getText();
		POB = PlaceOfBirthTxt.getText();
		String message = "REGS";
		message += " " + RegUsername + " " + RegPassword + " " + DOB + " " + POB;

		for (Integer m : MusicList)
		{
			message += " " + m;
			//String information = RegUsername + "\n" + DOB + "\n" + POB + "\n" + m.toString();
		}

		message += "\n";

		System.out.println(message);

		String reply = server_.send(message);

		switch (reply)
		{
			case "SUCCESS":
				this.setVisible(false);
				new Login(server_).setVisible(true);
				break;
			case "FAILEX":
				registerStatus.setText("Username aready registered");
				break;
			case "FAILDB":
				registerStatus.setText("Database error, try again later");
				break;
		}
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed

		Object Selection = MusicProfileCmb.getSelectedItem();
		String selectionName = Selection.toString();
		Integer selectionValue = 0;

		for (int i = 0; i < MusicTypes.size(); ++i)
		{
			if (MusicTypes.get(i).equals(selectionName))
			{
				selectionValue = i;
			}
		}

		if (MusicListString.contains(selectionValue))
		{
			return;
		}

		MusicList.add(selectionValue);
		MusicListString.add(selectionName);
		MusicProfileList.setListData(MusicListString);
    }//GEN-LAST:event_AddButtonActionPerformed

    private void RemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBtnActionPerformed
		Object Selection = MusicProfileList.getSelectedValue();
		MusicListString.remove(Selection);
		MusicProfileList.setListData(MusicListString);
		// TODO add your handling code here:
    }//GEN-LAST:event_RemoveBtnActionPerformed

    private void RegUsernameTxtCaretUpdate(javax.swing.event.CaretEvent evt)//GEN-FIRST:event_RegUsernameTxtCaretUpdate
    {//GEN-HEADEREND:event_RegUsernameTxtCaretUpdate
		if (RegUsernameTxt.getText().isEmpty())
		{
			RegisterButton.setEnabled(false);
		}
		else
		{
			RegisterButton.setEnabled(true);
		}
    }//GEN-LAST:event_RegUsernameTxtCaretUpdate

    private void PlaceOfBirthTxtCaretUpdate(javax.swing.event.CaretEvent evt)//GEN-FIRST:event_PlaceOfBirthTxtCaretUpdate
    {//GEN-HEADEREND:event_PlaceOfBirthTxtCaretUpdate
		if (PlaceOfBirthTxt.getText().isEmpty())
		{
			RegisterButton.setEnabled(false);
		}
		else
		{
			RegisterButton.setEnabled(true);
		}
    }//GEN-LAST:event_PlaceOfBirthTxtCaretUpdate

    private void DateOfBirthTxtCaretUpdate(javax.swing.event.CaretEvent evt)//GEN-FIRST:event_DateOfBirthTxtCaretUpdate
    {//GEN-HEADEREND:event_DateOfBirthTxtCaretUpdate
		if (DateOfBirthTxt.getText().isEmpty())
		{
			RegisterButton.setEnabled(false);
		}
		else
		{
			RegisterButton.setEnabled(true);
		}
    }//GEN-LAST:event_DateOfBirthTxtCaretUpdate

    private void RegPasswordTxtCaretUpdate(javax.swing.event.CaretEvent evt)//GEN-FIRST:event_RegPasswordTxtCaretUpdate
    {//GEN-HEADEREND:event_RegPasswordTxtCaretUpdate
		if (RegPasswordTxt.getText().isEmpty())
		{
			RegisterButton.setEnabled(false);
		}
		else
		{
			RegisterButton.setEnabled(true);
		}
    }//GEN-LAST:event_RegPasswordTxtCaretUpdate

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField DateOfBirthTxt;
    private javax.swing.JComboBox<String> MusicProfileCmb;
    private javax.swing.JList<String> MusicProfileList;
    private javax.swing.JTextField PlaceOfBirthTxt;
    private javax.swing.JTextField RegPasswordTxt;
    private javax.swing.JTextField RegUsernameTxt;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JButton RemoveBtn;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel registerStatus;
    // End of variables declaration//GEN-END:variables
}
